### ISSUE TITLE
Deeplseep issues / fix

### ISSUE THREAD

**Issue by jvgelder** [m5stack/M5-CoreInk#8]
I was having issues getting deep sleep to work using the battery (no usb power) and the regular esp functions `esp_deep_sleep_start` and `esp_sleep_enable_timer_wakeup()`.
When I realized it had a bat boost converter I managed it to get it to work by:
```cpp
pinMode(POWER_HOLD_PIN,OUTPUT);
digitalWrite(POWER_HOLD_PIN,HIGH);
gpio_hold(GPIO_NUM_12); // tell the esp to keep pin high even in sleep
```

I am not sure where this information belongs but i thought it might be useful for anyone else bonking his head against the wall.

**Comment by scudrunner** [comment]
this worked for me (Finally)      

   pinMode(POWER_HOLD_PIN,OUTPUT);
        digitalWrite(POWER_HOLD_PIN,HIGH);
        gpio_hold_en(GPIO_NUM_12); // tell the esp to keep pin high even in sleep
        esp_deep_sleep_start();

**Comment by johnwargo** [comment]
is it time to close this issue @jvgelder?  It's been open for years.

**Comment by jvgelder** [comment]
better late than never i guess but was this the fix? https://github.com/m5stack/M5Unified/commit/5986a80e89ec52f0598e2374d4264bc79eb54250  
I haven't  tested it my self but if deepsleep now automatically holds the power pin yes, but i don't see any references to documentation updates ?

**Comment by simenopsahl** [comment]
The ESP-IDF equivalent of this would be
```C
gpio_set_direction(POWER_HOLD_PIN, GPIO_MODE_OUTPUT); // Set output mode
gpio_set_level(POWER_HOLD_PIN, 1); // Set HIGH
gpio_hold_en(POWER_HOLD_PIN); // Hold value
gpio_deep_sleep_hold_en(); // Even in deep  #sleep
```
I found this to work for me in ESPHome
```YAML
esphome:
  comment: "M5Stack CoreInk"
  name: $devicename
  friendly_name: $devicename
  area: $location
  on_boot:
    then:
      # Bypass sleep arduino
#      - lambda: |-
#          pinMode(GPIO_NUM_12, OUTPUT);
#          digitalWrite(GPIO_NUM_12, HIGH);
#          gpio_hold_en(GPIO_NUM_12);
      # Bypass sleep esp-idf
      - lambda: |-
          gpio_set_direction(GPIO_NUM_12, GPIO_MODE_OUTPUT);
          gpio_set_level(GPIO_NUM_12, 1);
          gpio_hold_en(GPIO_NUM_12);
          gpio_deep_sleep_hold_en();
```
